name:           dotdrop
base:           core20
adopt-info:     version
summary:        Save your dotfiles once, deploy them everywhere
description: |
  Dotdrop makes the management of dotfiles between different hosts easy.
  It allows to store your dotfiles on git and automagically deploy different versions
  of the same file on different setups.

  It also allows to manage different sets of dotfiles.
  For example you can have a set of dotfiles for your home laptop and a different
  set for your office desktop. Those sets may overlap and different versions of
  the same dotfiles can be deployed on different predefined profiles.
  Or you may have a main set of dotfiles for your everyday's host and a sub-set you
  only need to deploy to temporary hosts (cloud VM, etc) that may be using a slightly
  different version of some of the dotfiles.
  It allows to store your dotfiles on git and automagically deploy
  different versions of the same file on different setups.

  Project page: https://github.com/deadc0de6/dotdrop

confinement:    strict
grade:          stable

apps:
  dotdrop:
    command:    bin/dotdrop
    plugs:
      - home

parts:
  dotdrop:
    plugin:     python
    source: ../../
    stage-packages:
      - file
  version:
    source: .
    plugin: nil
    override-build: |
      VERSION=""
      if [ hash git &>/dev/null ]; then
        VERSION=$(git describe --abbrev=0 --tags | sed 's/^v//g')
      fi
      if [ -z ${VERSION} ]; then
        VERSION=$(cat dotdrop/version.py | grep version | sed 's/^.*= .\(.*\).$/\1/g')
      fi
      [ -z "${VERSION}" ] && exit 1
      snapcraftctl set-version "${VERSION}"
