name: Release to aur
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  aur_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare AUR package
      run: |
        version=""
        if [ hash git &>/dev/null ]; then
          version=$(git describe --abbrev=0 --tags | sed 's/^v//g')
        fi
        if [ -z "${version}" ]; then
          version=$(cat dotdrop/version.py | grep version | sed 's/^.*= .\(.*\).$/\1/g')
        fi
        [ -z "${version}" ] && exit 1
        sed -i "s/^pkgver=.*$/pkgver=${version}/g" packages/arch-dotdrop/PKGBUILD
        cat packages/arch-dotdrop/PKGBUILD
    - name: Publish to aur
      uses: KSXGitHub/github-actions-deploy-aur@v3.0.0
      with:
        pkgname: dotdrop
        pkgbuild: ./packages/arch-dotdrop/PKGBUILD
        commit_username: ${{ secrets.AUR_USERNAME }}
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_message: "bump version"
